name: Python-CI

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Python version
        run: python --version
  security:
    runs-on: ubuntu-latest
    steps:
      - name: working dir
        run: pwd 
  
        