name: Python-CI

permissions:
  contents: read
env:
  APP_USER: production

on:
  push:
    branches:
      - main
      - feature
    paths:
      - "**.py"
      - "ci.yaml"
    

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  test:
    env:
      APP_USER: testing
    runs-on: ubuntu-latest   
    permissions:
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Python SETUP
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Python version
        run: python --version
      - name: installing dependencies
        run: pip install -r requirements.txt
      - name: LINTING
        run: ruff check .
      - name: TESTING
        env:
          PYTHONPATH: .
        run: pytest --junitxml=test-results.xml
      - name: uploading artifact
        uses: actions/upload-artifact@v4
        with:
            name: pytest-results
            path:  test-results.xml
      - name: environment variable check
        env:
          APP_USER: step variable
        run: echo "$APP_USER"
      - name: step variable
        run: echo "$APP_USER"
      
  lint:
    runs-on: ubuntu-latest
    permissions: {}
      
    steps:
      - name: GITHUB SHA
        run: echo $GITHUB_SHA
      - name: GITHUB REF
        run: echo $GITHUB_REF
      - name: DEMO_SECRET VALUE
        env:
          DEMO_SECRET: ${{secrets.DEMO_SECRET}}
        run: echo $DEMO_SECRET
      - name: GITHUB TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: echo $GITHUB_TOKEN
  security:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: printing env vari
        run: echo "$APP_USER"
  build:
    runs-on: ubuntu-latest
    needs: [lint,security,test]
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: building image
        run: docker build -t flask-app:$GITHUB_SHA .
      - name: starting container
        run: docker run -d --name CICD -p 8000:8000 flask-app:$GITHUB_SHA
      - name: HTTP SMOKE TEST
        run: |
          for i in {1..10}
          do
            if response=$(curl --fail http://localhost:8000); then
              echo "Application is ready"
              echo "$response"
              echo "$response" | grep -q "Hello from Docker!"
              exit 0
            fi

            echo "Application not ready yet. Attempt $i/10"
            sleep 1
          done

          echo "Application failed to become ready"
          exit 1
            - name: docker check
              if: always()
              run: docker ps -a
            - name: docker log
              if: always()
              run: docker logs CICD
  failure-handler:
    runs-on: ubuntu-latest
    needs: [lint,security,test]
    permissions: {}
    if: failure()
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name:  checkout ls -la
        run: ls -la 
  artifact-check:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v5
        with:
          name: pytest-results
      - name: Inspecting artifact
        run: cat test-results.xml
  aws_connectivity:
    runs-on: ubuntu-latest
    permissions:
      {}
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - name: checking aws
        run: aws sts get-caller-identity


     
  
        