name: Python-CI


env:
  APP_USER: production

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  test:
    env:
      APP_USER: testing
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: environment variable check
        env:
          APP_USER: step variable
        run: echo "$APP_USER"
      - name: step variable
        run: echo "$APP_USER"
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Python version
        run: python --version
  security:
    runs-on: ubuntu-latest
    steps:
      - name: printing env vari
        run: echo "$APP_USER"
  build:
    runs-on: ubuntu-latest
    needs: [lint,security,test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  failure-handler:
    runs-on: ubuntu-latest
    needs: [lint,security,test]
    if: failure()

    steps:
      - name:  checkout ls -la
        run: ls -la 
     
  
        